apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: developers-api-ingress
  labels:
    name: developers-api-ingress   
spec:
  rules:
  - host: fake-developers.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: developers-api-service
            port: 
              number: 80
